SQLALCHEMY_DATABASE_URI = 'mysql://root:root@localhost/arh'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_POOL_RECYCLE = 10
SQLALCHEMY_POOL_SIZE = 200
SECRET_KEY = 'You-did-not-pray-pink-elephant'
CORS_SUPPORTS_CREDENTIALS = True
